from Tkinter import*
from tkMessageBox import*
def start():
    strt=Tk()
    strt.configure(bg='')
    strt.title('PROJECT INFO')
    strt.state('zoomed')
    Frame(strt,bg='cyan',height=10000,width=30,bd=2).place(relx=0.98)
    Frame(strt,bg='cyan',height=30,width=10000,bd=2).place(rely=0.98)
    Frame(strt,bg='cyan',height=10000,width=30,bd=2).place(relx=0)
    Frame(strt,bg='cyan',height=30,width=10000,bd=2).place(rely=0)
    Frame(strt,bg='dark orange3',height=10000,width=10,bd=2).place(relx=0.93)
    Frame(strt,bg='dark orange3',height=10,width=10000,bd=2).place(rely=0.93)
    Frame(strt,bg='dark orange3',height=10000,width=10,bd=2).place(relx=0.04)
    Frame(strt,bg='dark orange3',height=10,width=10000,bd=2).place(rely=0.06)  
    Label(strt,text=' PROJECT',font="times 22 bold italic",bg='black',fg='white').place(relx=.37,rely=.08)
    Label(strt,text='B4 (BY)',font='times 20 bold',fg="black").place(relx=0.09,rely=0.28)
    Label(strt,text='PROJECT:FARMERBUDDY',font='times 20 bold',fg="black").place(relx=0.09,rely=0.34)
    Label(strt,text='SUBMITTED BY MADHULIKA RICHHARIYA (161B116)',font="times 22 bold italic",bg='black',fg='white').place(relx=.39,rely=0.36)  
    strt.destroy()
    strt.after(5000,dest)
    strt.mainloop()

start()
root=Tk()
root.configure(bg='black')
root.title("project")
root.attributes("-fullscreen",True)
Label(root,text='AGRICULTURE MARKET',font="times 26 bold italic",bg='black',fg='white').place(relx=.37,rely=.08)
Frame(root,bg='dark orange3',height=10000,width=30,bd=2).place(relx=0.98)
Frame(root,bg='dark orange3',height=30,width=10000,bd=2).place(rely=0.98)
Frame(root,bg='dark orange3',height=10000,width=30,bd=2).place(relx=0)
Frame(root,bg='dark orange3',height=30,width=10000,bd=2).place(rely=0)
Frame(root,bg='dark orange3',height=10000,width=10,bd=2).place(relx=0.93)
Frame(root,bg='dark orange3',height=10,width=10000,bd=2).place(rely=0.93)
Frame(root,bg='dark orange3',height=10000,width=10,bd=2).place(relx=0.04)
Frame(root,bg='dark orange3',height=10,width=10000,bd=2).place(rely=0.06)
import sqlite3
con=sqlite3.Connection('midb')
cur=con.cursor()
cur.execute('create table if not exists sel(sname varchar(20),scode number(5) primary key,splace varchar(20),scrop varchar(10),squan number(5),squal varchar(20),sprice number(20),scontact number(10))')
cur.execute('create table if not exists byer(bname varchar(20),bcode number(5) primary key,bplace varchar(20),bcontact number(10))')

def fun(): 
    root=Tk()
    root.title("farmer")
    root.configure(bg='medium purple3')
    root.attributes("-fullscreen",True)
    Frame(root,bg='purple4',height=10000,width=30,bd=2).place(relx=0.98)
    Frame(root,bg='purple4',height=30,width=10000,bd=2).place(rely=0.98)
    Frame(root,bg='purple4',height=10000,width=30,bd=2).place(relx=0)
    Frame(root,bg='purple4',height=30,width=10000,bd=2).place(rely=0)
    Frame(root,bg='purple4',height=10000,width=10,bd=2).place(relx=0.93)
    Frame(root,bg='purple4',height=10,width=10000,bd=2).place(rely=0.93)
    Frame(root,bg='purple4',height=10000,width=10,bd=2).place(relx=0.04)
    Frame(root,bg='purple4',height=10,width=10000,bd=2).place(rely=0.06)
    Label(root,text='SELLER RECORD KEEPING SYSTEM :',font='times 26 bold italic',fg='black',bg='medium purple3').place(relx=0.06,rely=0.08)
    e=Entry(root,width=20,bd=3,font="times 20 bold")
    e.place(relx=0.3,rely=0.21)
    Label(root,text=' ENTER YOUR NAME:',font='times 20 bold italic',fg='black',bg='medium purple3').place(relx=0.06,rely=0.20)
    f=IntVar()
    f=Entry(root,width=20,bd=3,font="times 20 bold",)
    f.place(relx=0.3,rely=0.26)
    Label(root,text=' ENTER YOUR CODE :',font='times 20 bold italic',fg='black',bg='medium purple3').place(relx=0.06,rely=0.26)
    e1=Entry(root,width=20,bd=3,font="times 20 bold",)
    e1.place(relx=0.3,rely=0.32)
    Label(root,text='PLACE:',font='times 20 bold italic',fg='black',bg='medium purple3').place(relx=0.06,rely=0.32)
    e2=Entry(root,width=20,bd=3,font="times 20 bold",)
    e2.place(relx=0.3,rely=0.38)
    Label(root,text='CROP',font='times 20 bold italic',fg='black',bg='medium purple3').place(relx=0.06,rely=0.38)
    e3=Entry(root,width=20,bd=3,font="times 20 bold",)
    e3.place(relx=0.3,rely=0.44)
    Label(root,text='QUANTITY',font='times 20 bold italic',fg='black',bg='medium purple3').place(relx=0.06,rely=0.44)
    e4=StringVar()
    e4=Entry(root,width=20,bd=3,font="times 20 bold",)
    e4.place(relx=0.3,rely=0.50)
    Label(root,text='QUALITY',font='times 20 bold italic',fg='black',bg='medium purple3').place(relx=0.06,rely=0.50)
    e5=IntVar()
    e5=Entry(root,width=20,bd=3,font="times 20 bold",)
    e5.place(relx=0.3,rely=0.56)
    Label(root,text='EXPECTED PRICE',font='times 20 bold italic',fg='black',bg='medium purple3').place(relx=0.06,rely=0.56)
    e6=IntVar()
    e6=Entry(root,width=20,bd=3,font="times 20 bold",)
    e6.place(relx=0.3,rely=0.62)
    Label(root,text='CONACT NO.',font='times 20 bold italic',fg='black',bg='medium purple3').place(relx=0.06,rely=0.62)
    id=IntVar()
    id=Entry(root,width=20,bd=3,font="times 20 bold",)
    id.place(relx=0.69,rely=0.26)
    Label(root,text='ID LOGIN(CODE):',font='times 20 bold italic',fg='black',bg='medium purple3').place(relx=0.55,rely=0.20)
    Label(root,text='SELLER NO.',font='times 20 bold italic',fg='black',bg='medium purple3').place(relx=0.55,rely=0.26)

    def insert():
        if((e.get()=='')or(f.get()=='')or(e1.get()=='')or(e2.get=='')or(e3.get()=='')or(e4.get()=='')or(e5.get()=='')or(e6.get=='')):
            showerror('error','you left a feild empty')
        else:
            y=[(f.get())]
            cur.execute("select * from sel where scode=(?)",y)
            r=cur.fetchall()
            if(len(r)!=0):
                showerror('ERROR','ALREADY USED CODE ENTER ANOTHER CODE')
            else:
                v=[(e.get(),f.get(),e1.get(),e2.get(),e3.get(),e4.get(),e5.get(),e6.get())]
                cur.executemany("insert into sel values(?,?,?,?,?,?,?,?)",v)
                con.commit()
                e.delete(0,END)
                f.delete(0,END)
                e1.delete(0,END)
                e2.delete(0,END)
                e3.delete(0,END)
                e4.delete(0,END)
                e5.delete(0,END)
                e6.delete(0,END)
    Button(root,text="INSERT",font='Helvetica 9 bold',bg='purple',bd=5,height=2,width=10,command=insert).place(relx=0.06,rely=0.80)
    def show():
          n=[(id.get())]
          cur.execute("select * from sel where scode=(?)",n)
          a=cur.fetchall()
          Label(root,text=a).place(relx=0.53,rely=0.44)
    Button(root,text="SHOW",font='Helvetica 9 bold',bg='purple',bd=5,height=2,width=10,command=show).place(relx=0.6,rely=0.80)
    Button(root,text="BACK",font='Helvetica 9 bold',bg='salmon',bd=5,height=1,width=10,command=lambda:root.destroy()).place(relx=0.8,rely=0.80)
Button(root,text="SELLER",font='times 18 bold italic',bg='darkorange2',bd=10,height=4,width=16,command=fun).place(relx=0.20,rely=0.30)
def bun():
    root=Tk()
    root.configure(bg='cyan2')
    root.title('buyer')
    root.attributes("-fullscreen",True)
    Frame(root,bg='cyan4',height=10000,width=30,bd=2).place(relx=0.98)
    Frame(root,bg='cyan4',height=30,width=10000,bd=2).place(rely=0.98)
    Frame(root,bg='cyan4',height=10000,width=30,bd=2).place(relx=0)
    Frame(root,bg='cyan4',height=30,width=10000,bd=2).place(rely=0)
    Frame(root,bg='cyan4',height=10000,width=10,bd=2).place(relx=0.93)
    Frame(root,bg='cyan4',height=10,width=10000,bd=2).place(rely=0.93)
    Frame(root,bg='cyan4',height=10000,width=10,bd=2).place(relx=0.04)
    Frame(root,bg='cyan4',height=10,width=10000,bd=2).place(rely=0.06)
    Label(root,text='BUYER RECORD KEEPING SYSTEM:',font='times 20 bold',bg='cyan2').place(relx=0.06,rely=0.08)
    e=Entry(root,width=20,bd=3,font="times 20 bold")
    e.place(relx=0.3,rely=0.21)
    Label(root,text=' ENTER YOUR NAME:',font='times 20 bold italic',fg='black',bg='cyan2').place(relx=0.06,rely=0.20)
    f=IntVar()
    f=Entry(root,width=20,bd=3,font="times 20 bold",)
    f.place(relx=0.3,rely=0.26)
    Label(root,text=' ENTER YOUR CODE :',font='times 20 bold italic',fg='black',bg='cyan2').place(relx=0.06,rely=0.26)
    e1=Entry(root,width=20,bd=3,font="times 20 bold",)
    e1.place(relx=0.3,rely=0.32)
    Label(root,text='PLACE:',font='times 20 bold italic',fg='black',bg='cyan2').place(relx=0.06,rely=0.32)
    e6=IntVar()
    e6=Entry(root,width=20,bd=3,font="times 20 bold",)
    e6.place(relx=0.3,rely=0.38)
    Label(root,text='CONACT NO.',font='times 20 bold italic',fg='black',bg='cyan2').place(relx=0.06,rely=0.38)
    Label(root,text='CHOICE :',font='times 20 bold italic',fg='black',bg='cyan2').place(relx=0.06,rely=0.50)
    e2=StringVar()
    e2=Entry(root,width=20,bd=3,font="times 20 bold",)
    e2.place(relx=0.3,rely=0.56)
    Label(root,text='CROP',font='times 20 bold italic',fg='black',bg='cyan2').place(relx=0.06,rely=0.56)
    e3=Entry(root,width=20,bd=3,font="times 20 bold",)
    e3.place(relx=0.3,rely=0.62)
    Label(root,text='QUANTITY',font='times 20 bold italic',fg='black',bg='cyan2').place(relx=0.06,rely=0.62)
    e4=IntVar()
    e4=Entry(root,width=20,bd=3,font="times 20 bold",)
    e4.place(relx=0.3,rely=0.68)
    Label(root,text='EXPECTED PRICE',font='times 20 bold italic',fg='black',bg='cyan2').place(relx=0.06,rely=0.68)
    id=IntVar()
    id=Entry(root,width=20,bd=3,font="times 20 bold",)
    id.place(relx=0.67,rely=0.26)
    Label(root,text='BUYER LOGIN (CODE):',font='times 20 bold italic',fg='black',bg='cyan2').place(relx=0.55,rely=0.20)
    Label(root,text='BUYER NO.',font='times 20 bold italic',fg='black',bg='cyan2').place(relx=0.55,rely=0.26)
    Label(root,text="display buyer list",font='Helvetica 9 bold',fg='black',bg='cyan2').place(relx=0.2,rely=0.84)  
    def insert():
        if((e.get()=='')or(f.get()=='')or(e1.get()=='')or(e2.get=='')or(e6.get=='')):
            showerror('error','you left a feild empty')
        else:
            y=[(f.get())]
            cur.execute("select * from byer where bcode=(?)",y)
            r=cur.fetchall()
            if(len(r)!=0):
                showerror('ERROR','ALREADY USED CODE ENTER ANOTHER CODE')
            else:
                v=[(e.get(),f.get(),e1.get(),e6.get())]
                cur.executemany("insert into byer values(?,?,?,?)",v)
                con.commit()
                e.delete(0,END)
                f.delete(0,END)
                e1.delete(0,END)
                e2.delete(0,END)
            
    Button(root,text="INSERT",font='Helvetica 9 bold',bg='dodgerblue2',bd=5,height=1,width=10,command=insert).place(relx=0.2,rely=0.44)
    def show():
          n=[(id.get())]
          cur.execute("select * from byer where bcode=(?)",n)
          a=cur.fetchall()
          Label(root,text=a).place(relx=0.5,rely=0.46)
          e3.delete(0,END)
          e4.delete(0,END)
    Button(root,text="SHOW",font='Helvetica 9 bold',bg='dodgerblue2',bd=5,height=1,width=10,command=show).place(relx=0.7,rely=0.44)
    def display():
         root=Tk()
         root.configure(bg='cadetblue1')
         x=[(e2.get())]
         cur.execute("select * from sel where scrop=(?)",x)
         p=cur.fetchall()
         Label(root,text=p,font='times 12 bold',fg='black',bg='cadetblue1').place(relx=0,rely=0.08)
         Label(root,text="BUYER LIST",font='Helvetica 20 bold',bg='cadetblue1',fg='black').place(relx=0.5,rely=0)
         def dis():
              showinfo('info','to buy the product pls contact the number provided in the end of lists')
         Button(root,text="BUY",font='Helvetica 9 bold',bg='dodgerblue2',bd=5,height=1,width=10,command=dis).place(relx=0.6,rely=0.78)  
    Button(root,text="display",font='Helvetica 9 bold',bg='dodgerblue2',bd=5,height=1,width=10,command=display,).place(relx=0.2,rely=0.80)  
    Button(root,text="Back",font='Helvetica 9 bold',bg='salmon',bd=5,height=1,width=10,command=lambda:root.destroy()).place(relx=.7,rely=.80)

Button(root,text="BUYER",font='times 18 bold italic',bg='darkorange2',bd=10,height=4,width=16,command=bun).place(relx=0.63,rely=0.30)
Button(root,text="CLOSE",font='Helvetica 9 bold',bg='salmon',bd=5,height=2,width=10,command=lambda:root.destroy()).place(relx=.7,rely=.7)
root.mainloop()





